[project]
name = "cahiers-pour-decider-et-agir"
version = "0.1.0"
description = "Data For Good : restitution des cahiers citoyens de 2019 avec l'association Des cahiers pour décider et agir"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
    "tox",
    "tox-uv",
]

[tool.ruff]
target-version = "py314"

[tool.pytest.ini_options]
pythonpath = ["."]
