# Generated by Django 6.1.2 on 2026-10-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "département",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "région",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COM", "commune"),
                            ("COMD", "commune déléguée"),
                            ("COMA", "commune associée"),
                            ("ARM", "arrondissement municipal"),
                        ],
                        max_length=4,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("code_courant", models.CharField(blank=True, max_length=5)),
                ("nom_courant", models.CharField(blank=True, max_length=100)),
                (
                    "commune_parente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rattachees",
                        to="territoires.commune",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communes",
                        to="territoires.departement",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departements",
                to="territoires.region",
            ),
        ),
    ]
