# Generated by Django 6.1.2 on 2026-10-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("territoires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.CharField(max_length=100, unique=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("CC", "cahier citoyen"),
                            ("CO", "courrier"),
                            ("CR", "compte rendu de réunion"),
                            ("IL", "compte rendu de réunion par courriel"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D", "dactylographié"),
                            ("M", "manuscrit"),
                            ("MD", "mixte"),
                        ],
                        max_length=2,
                    ),
                ),
                ("code_postal", models.CharField(blank=True, max_length=5)),
                ("date_depot", models.DateField(blank=True, null=True)),
                ("numero", models.PositiveIntegerField(blank=True, null=True)),
                ("code_insee", models.CharField(blank=True, max_length=6)),
                ("nombre_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("pdf", models.FileField(blank=True, upload_to="documents/")),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="territoires.commune",
                    ),
                ),
            ],
            options={
                "ordering": ["fichier"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("delimitation", "délimitation des contributions"),
                            ("transcription", "transcription"),
                            ("anonymisation", "anonymisation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                ("auteur", models.CharField(max_length=100)),
                ("modele", models.CharField(blank=True, max_length=200)),
                ("parametres", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("cree", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-cree"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("actif", True)),
                        fields=("genre",),
                        name="un_run_actif_par_genre",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vierge", "vierge"),
                            ("dactylographiee", "dactylographiée"),
                            ("mixte", "mixte"),
                            ("manuscrite", "manuscrite"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rotation",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "0°"), (90, "90°"), (180, "180°"), (270, "270°")],
                        default=0,
                    ),
                ),
                ("service", models.BooleanField(default=False)),
                ("ouverture", models.BooleanField(default=False)),
                ("texte", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="cahiers.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "numero"), name="page_unique_par_document"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rang", models.PositiveIntegerField()),
                ("page_debut", models.PositiveIntegerField()),
                ("y_debut", models.FloatField(blank=True, null=True)),
                ("page_fin", models.PositiveIntegerField()),
                ("y_fin", models.FloatField(blank=True, null=True)),
                ("origine", models.CharField(blank=True, max_length=50)),
                ("texte", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="cahiers.document",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="cahiers.run",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "rang"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "document", "rang"), name="rang_unique_par_run"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("page_fin__gte", models.F("page_debut"))),
                        name="fin_apres_debut",
                    ),
                ],
            },
        ),
    ]
